properties = [
    {
        "name": "Old Kent Road",
        "position": 1,
        "type": "Property",
        "set": "Brown",
        "price": 60,
        "rent": 2.0,
        "rent_withset": 4.0,
        "rent_1house": 10.0,
        "rent_2house": 30.0,
        "rent_3house": 90.0,
        "rent_4house": 160.0,
        "rent_hotel": 250.0,
        "house_cost": 50.0,
        "mortgage": 30,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Whitechapel Road",
        "position": 3,
        "type": "Property",
        "set": "Brown",
        "price": 60,
        "rent": 4.0,
        "rent_withset": 8.0,
        "rent_1house": 20.0,
        "rent_2house": 60.0,
        "rent_3house": 180.0,
        "rent_4house": 320.0,
        "rent_hotel": 450.0,
        "house_cost": 50.0,
        "mortgage": 30,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Kings Cross Station",
        "position": 5,
        "type": "Property",
        "set": "Station",
        "price": 200,
        "rent": None,
        "rent_withset": None,
        "rent_1house": None,
        "rent_2house": None,
        "rent_3house": None,
        "rent_4house": None,
        "rent_hotel": None,
        "house_cost": None,
        "mortgage": 100,
        "station_rent_1": 25.0,
        "station_rent_2": 50.0,
        "station_rent_3": 100.0,
        "station_rent_4": 200.0,
        "owner": None,
    },
    {
        "name": "The Angel Islington",
        "position": 6,
        "type": "Property",
        "set": "Light blue",
        "price": 100,
        "rent": 6.0,
        "rent_withset": 12.0,
        "rent_1house": 30.0,
        "rent_2house": 90.0,
        "rent_3house": 270.0,
        "rent_4house": 400.0,
        "rent_hotel": 550.0,
        "house_cost": 50.0,
        "mortgage": 50,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Euston Road",
        "position": 8,
        "type": "Property",
        "set": "Light blue",
        "price": 100,
        "rent": 6.0,
        "rent_withset": 12.0,
        "rent_1house": 30.0,
        "rent_2house": 90.0,
        "rent_3house": 270.0,
        "rent_4house": 400.0,
        "rent_hotel": 550.0,
        "house_cost": 50.0,
        "mortgage": 50,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Pentonville Road",
        "position": 9,
        "type": "Property",
        "set": "Light blue",
        "price": 120,
        "rent": 8.0,
        "rent_withset": 16.0,
        "rent_1house": 40.0,
        "rent_2house": 100.0,
        "rent_3house": 300.0,
        "rent_4house": 450.0,
        "rent_hotel": 600.0,
        "house_cost": 50.0,
        "mortgage": 60,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Pall Mall",
        "position": 11,
        "type": "Property",
        "set": "Pink",
        "price": 140,
        "rent": 10.0,
        "rent_withset": 20.0,
        "rent_1house": 50.0,
        "rent_2house": 150.0,
        "rent_3house": 450.0,
        "rent_4house": 625.0,
        "rent_hotel": 750.0,
        "house_cost": 100.0,
        "mortgage": 70,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Whitehall",
        "position": 13,
        "type": "Property",
        "set": "Pink",
        "price": 140,
        "rent": 10.0,
        "rent_withset": 20.0,
        "rent_1house": 50.0,
        "rent_2house": 150.0,
        "rent_3house": 450.0,
        "rent_4house": 625.0,
        "rent_hotel": 750.0,
        "house_cost": 100.0,
        "mortgage": 70,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Northumberland Avenue",
        "position": 14,
        "type": "Property",
        "set": "Pink",
        "price": 160,
        "rent": 12.0,
        "rent_withset": 24.0,
        "rent_1house": 60.0,
        "rent_2house": 180.0,
        "rent_3house": 500.0,
        "rent_4house": 700.0,
        "rent_hotel": 900.0,
        "house_cost": 100.0,
        "mortgage": 80,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Marylebone Station",
        "position": 15,
        "type": "Property",
        "set": "Station",
        "price": 200,
        "rent": None,
        "rent_withset": None,
        "rent_1house": None,
        "rent_2house": None,
        "rent_3house": None,
        "rent_4house": None,
        "rent_hotel": None,
        "house_cost": None,
        "mortgage": 100,
        "station_rent_1": 25.0,
        "station_rent_2": 50.0,
        "station_rent_3": 100.0,
        "station_rent_4": 200.0,
        "owner": None,
    },
    {
        "name": "Bow Street",
        "position": 16,
        "type": "Property",
        "set": "Orange",
        "price": 180,
        "rent": 14.0,
        "rent_withset": 28.0,
        "rent_1house": 70.0,
        "rent_2house": 200.0,
        "rent_3house": 550.0,
        "rent_4house": 750.0,
        "rent_hotel": 950.0,
        "house_cost": 100.0,
        "mortgage": 90,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Marlborough Street",
        "position": 18,
        "type": "Property",
        "set": "Orange",
        "price": 180,
        "rent": 14.0,
        "rent_withset": 28.0,
        "rent_1house": 70.0,
        "rent_2house": 200.0,
        "rent_3house": 550.0,
        "rent_4house": 750.0,
        "rent_hotel": 950.0,
        "house_cost": 100.0,
        "mortgage": 90,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Vine Street",
        "position": 19,
        "type": "Property",
        "set": "Orange",
        "price": 200,
        "rent": 16.0,
        "rent_withset": 32.0,
        "rent_1house": 80.0,
        "rent_2house": 220.0,
        "rent_3house": 600.0,
        "rent_4house": 800.0,
        "rent_hotel": 1000.0,
        "house_cost": 100.0,
        "mortgage": 100,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Strand",
        "position": 21,
        "type": "Property",
        "set": "Red",
        "price": 220,
        "rent": 18.0,
        "rent_withset": 36.0,
        "rent_1house": 90.0,
        "rent_2house": 250.0,
        "rent_3house": 700.0,
        "rent_4house": 875.0,
        "rent_hotel": 1050.0,
        "house_cost": 150.0,
        "mortgage": 110,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Fleet Street",
        "position": 23,
        "type": "Property",
        "set": "Red",
        "price": 220,
        "rent": 18.0,
        "rent_withset": 36.0,
        "rent_1house": 90.0,
        "rent_2house": 250.0,
        "rent_3house": 700.0,
        "rent_4house": 875.0,
        "rent_hotel": 1050.0,
        "house_cost": 150.0,
        "mortgage": 110,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Trafalgar Square",
        "position": 24,
        "type": "Property",
        "set": "Red",
        "price": 240,
        "rent": 20.0,
        "rent_withset": 40.0,
        "rent_1house": 100.0,
        "rent_2house": 300.0,
        "rent_3house": 750.0,
        "rent_4house": 925.0,
        "rent_hotel": 1100.0,
        "house_cost": 150.0,
        "mortgage": 120,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Fenchurch St. Station",
        "position": 25,
        "type": "Property",
        "set": "Station",
        "price": 200,
        "rent": None,
        "rent_withset": None,
        "rent_1house": None,
        "rent_2house": None,
        "rent_3house": None,
        "rent_4house": None,
        "rent_hotel": None,
        "house_cost": None,
        "mortgage": 100,
        "station_rent_1": 25.0,
        "station_rent_2": 50.0,
        "station_rent_3": 100.0,
        "station_rent_4": 200.0,
        "owner": None,
    },
    {
        "name": "Leicester Square",
        "position": 26,
        "type": "Property",
        "set": "Yellow",
        "price": 260,
        "rent": 22.0,
        "rent_withset": 44.0,
        "rent_1house": 110.0,
        "rent_2house": 330.0,
        "rent_3house": 800.0,
        "rent_4house": 975.0,
        "rent_hotel": 1150.0,
        "house_cost": 150.0,
        "mortgage": 130,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Coventry Street",
        "position": 27,
        "type": "Property",
        "set": "Yellow",
        "price": 260,
        "rent": 22.0,
        "rent_withset": 44.0,
        "rent_1house": 110.0,
        "rent_2house": 330.0,
        "rent_3house": 800.0,
        "rent_4house": 975.0,
        "rent_hotel": 1150.0,
        "house_cost": 150.0,
        "mortgage": 130,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Piccadilly",
        "position": 29,
        "type": "Property",
        "set": "Yellow",
        "price": 280,
        "rent": 24.0,
        "rent_withset": 48.0,
        "rent_1house": 120.0,
        "rent_2house": 360.0,
        "rent_3house": 850.0,
        "rent_4house": 1025.0,
        "rent_hotel": 1200.0,
        "house_cost": 150.0,
        "mortgage": 140,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Regent Street",
        "position": 31,
        "type": "Property",
        "set": "Green",
        "price": 300,
        "rent": 26.0,
        "rent_withset": 52.0,
        "rent_1house": 130.0,
        "rent_2house": 390.0,
        "rent_3house": 900.0,
        "rent_4house": 1100.0,
        "rent_hotel": 1275.0,
        "house_cost": 200.0,
        "mortgage": 150,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Oxford Street",
        "position": 32,
        "type": "Property",
        "set": "Green",
        "price": 300,
        "rent": 26.0,
        "rent_withset": 52.0,
        "rent_1house": 130.0,
        "rent_2house": 390.0,
        "rent_3house": 900.0,
        "rent_4house": 1100.0,
        "rent_hotel": 1275.0,
        "house_cost": 200.0,
        "mortgage": 150,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Bond Street",
        "position": 34,
        "type": "Property",
        "set": "Green",
        "price": 320,
        "rent": 28.0,
        "rent_withset": 56.0,
        "rent_1house": 150.0,
        "rent_2house": 450.0,
        "rent_3house": 1000.0,
        "rent_4house": 1200.0,
        "rent_hotel": 1400.0,
        "house_cost": 200.0,
        "mortgage": 160,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Liverpool St. Station",
        "position": 35,
        "type": "Property",
        "set": "Station",
        "price": 200,
        "rent": None,
        "rent_withset": None,
        "rent_1house": None,
        "rent_2house": None,
        "rent_3house": None,
        "rent_4house": None,
        "rent_hotel": None,
        "house_cost": None,
        "mortgage": 100,
        "station_rent_1": 25.0,
        "station_rent_2": 50.0,
        "station_rent_3": 100.0,
        "station_rent_4": 200.0,
        "owner": None,
    },
    {
        "name": "Park Lane",
        "position": 37,
        "type": "Property",
        "set": "Blue",
        "price": 350,
        "rent": 35.0,
        "rent_withset": 70.0,
        "rent_1house": 175.0,
        "rent_2house": 500.0,
        "rent_3house": 1100.0,
        "rent_4house": 1300.0,
        "rent_hotel": 1500.0,
        "house_cost": 200.0,
        "mortgage": 175,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
    {
        "name": "Mayfair",
        "position": 39,
        "type": "Property",
        "set": "Blue",
        "price": 400,
        "rent": 50.0,
        "rent_withset": 100.0,
        "rent_1house": 200.0,
        "rent_2house": 600.0,
        "rent_3house": 1400.0,
        "rent_4house": 1700.0,
        "rent_hotel": 2000.0,
        "house_cost": 200.0,
        "mortgage": 200,
        "station_rent_1": None,
        "station_rent_2": None,
        "station_rent_3": None,
        "station_rent_4": None,
        "owner": None,
    },
]
