spaces = [
    {"name": "Go", "position": 0, "type": "Go", "set": None, "landed_on": 0.0},
    {
        "name": "Old Kent Road",
        "position": 1,
        "type": "Property",
        "set": "Brown",
        "landed_on": 0.0,
    },
    {
        "name": "Community Chest",
        "position": 2,
        "type": "Community Chest",
        "set": None,
        "landed_on": 0.0,
    },
    {
        "name": "Whitechapel Road",
        "position": 3,
        "type": "Property",
        "set": "Brown",
        "landed_on": 0.0,
    },
    {"name": "Income Tax", "position": 4, "type": "Tax", "set": None, "landed_on": 0.0},
    {
        "name": "Kings Cross Station",
        "position": 5,
        "type": "Property",
        "set": "Station",
        "landed_on": 0.0,
    },
    {
        "name": "The Angel Islington",
        "position": 6,
        "type": "Property",
        "set": "Light blue",
        "landed_on": 0.0,
    },
    {"name": "Chance", "position": 7, "type": "Chance", "set": None, "landed_on": 0.0},
    {
        "name": "Euston Road",
        "position": 8,
        "type": "Property",
        "set": "Light blue",
        "landed_on": 0.0,
    },
    {
        "name": "Pentonville Road",
        "position": 9,
        "type": "Property",
        "set": "Light blue",
        "landed_on": 0.0,
    },
    {
        "name": "Just Visiting",
        "position": 10,
        "type": "Just visiting",
        "set": None,
        "landed_on": 0.0,
    },
    {"name": "Jail", "position": 10.5, "type": "Jail", "set": None, "landed_on": 0.0},
    {
        "name": "Pall Mall",
        "position": 11,
        "type": "Property",
        "set": "Pink",
        "landed_on": 0.0,
    },
    {
        "name": "Electric Company",
        "position": 12,
        "type": "Property",
        "set": "Utility",
        "landed_on": 0.0,
    },
    {
        "name": "Whitehall",
        "position": 13,
        "type": "Property",
        "set": "Pink",
        "landed_on": 0.0,
    },
    {
        "name": "Northumberland Avenue",
        "position": 14,
        "type": "Property",
        "set": "Pink",
        "landed_on": 0.0,
    },
    {
        "name": "Marylebone Station",
        "position": 15,
        "type": "Property",
        "set": "Station",
        "landed_on": 0.0,
    },
    {
        "name": "Bow Street",
        "position": 16,
        "type": "Property",
        "set": "Orange",
        "landed_on": 0.0,
    },
    {
        "name": "Community Chest",
        "position": 17,
        "type": "Community Chest",
        "set": None,
        "landed_on": 0.0,
    },
    {
        "name": "Marlborough Street",
        "position": 18,
        "type": "Property",
        "set": "Orange",
        "landed_on": 0.0,
    },
    {
        "name": "Vine Street",
        "position": 19,
        "type": "Property",
        "set": "Orange",
        "landed_on": 0.0,
    },
    {
        "name": "Free Parking",
        "position": 20,
        "type": "Free Parking",
        "set": None,
        "landed_on": 0.0,
    },
    {
        "name": "Strand",
        "position": 21,
        "type": "Property",
        "set": "Red",
        "landed_on": 0.0,
    },
    {"name": "Chance", "position": 22, "type": "Chance", "set": None, "landed_on": 0.0},
    {
        "name": "Fleet Street",
        "position": 23,
        "type": "Property",
        "set": "Red",
        "landed_on": 0.0,
    },
    {
        "name": "Trafalgar Square",
        "position": 24,
        "type": "Property",
        "set": "Red",
        "landed_on": 0.0,
    },
    {
        "name": "Fenchurch St. Station",
        "position": 25,
        "type": "Property",
        "set": "Station",
        "landed_on": 0.0,
    },
    {
        "name": "Leicester Square",
        "position": 26,
        "type": "Property",
        "set": "Yellow",
        "landed_on": 0.0,
    },
    {
        "name": "Coventry Street",
        "position": 27,
        "type": "Property",
        "set": "Yellow",
        "landed_on": 0.0,
    },
    {
        "name": "Water Works",
        "position": 28,
        "type": "Property",
        "set": "Utility",
        "landed_on": 0.0,
    },
    {
        "name": "Piccadilly",
        "position": 29,
        "type": "Property",
        "set": "Yellow",
        "landed_on": 0.0,
    },
    {
        "name": "Go To Jail",
        "position": 30,
        "type": "Jail",
        "set": None,
        "landed_on": 0.0,
    },
    {
        "name": "Regent Street",
        "position": 31,
        "type": "Property",
        "set": "Green",
        "landed_on": 0.0,
    },
    {
        "name": "Oxford Street",
        "position": 32,
        "type": "Property",
        "set": "Green",
        "landed_on": 0.0,
    },
    {
        "name": "Community Chest",
        "position": 33,
        "type": "Community Chest",
        "set": None,
        "landed_on": 0.0,
    },
    {
        "name": "Bond Street",
        "position": 34,
        "type": "Property",
        "set": "Green",
        "landed_on": 0.0,
    },
    {
        "name": "Liverpool St. Station",
        "position": 35,
        "type": "Property",
        "set": "Station",
        "landed_on": 0.0,
    },
    {"name": "Chance", "position": 36, "type": "Chance", "set": None, "landed_on": 0.0},
    {
        "name": "Park Lane",
        "position": 37,
        "type": "Property",
        "set": "Blue",
        "landed_on": 0.0,
    },
    {"name": "Super Tax", "position": 38, "type": "Tax", "set": None, "landed_on": 0.0},
    {
        "name": "Mayfair",
        "position": 39,
        "type": "Property",
        "set": "Blue",
        "landed_on": 0.0,
    },
]
